<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb\BlockNotification;

use UnexpectedValueException;

/**
 * State of the block in relation to the chain.
 *
 * Protobuf type <code>pb.BlockNotification.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>CONNECTED = 0;</code>
     */
    const CONNECTED = 0;
    /**
     * Generated from protobuf enum <code>DISCONNECTED = 1;</code>
     */
    const DISCONNECTED = 1;

    private static $valueToName = [
        self::CONNECTED => 'CONNECTED',
        self::DISCONNECTED => 'DISCONNECTED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Pb\BlockNotification_Type::class);

