<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Metadata for identifying and validating a block
 *
 * Generated from protobuf message <code>pb.BlockInfo</code>
 */
class BlockInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The double sha256 hash of the six header fields in the first 80 bytes
     * of the block, when encoded according the bitcoin protocol, little-endian.
     * sha256(sha256(encoded_header))
     *
     * Generated from protobuf field <code>bytes hash = 1;</code>
     */
    protected $hash = '';
    /**
     * The block number, an incremental index for each block mined.
     *
     * Generated from protobuf field <code>int32 height = 2;</code>
     */
    protected $height = 0;
    /**
     * A version number to track software/protocol upgrades.
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     */
    protected $version = 0;
    /**
     * Hash of the previous block, little-endian.
     *
     * Generated from protobuf field <code>bytes previous_block = 4;</code>
     */
    protected $previous_block = '';
    /**
     * The root of the Merkle Tree built from all transactions in the block, little-endian.
     *
     * Generated from protobuf field <code>bytes merkle_root = 5;</code>
     */
    protected $merkle_root = '';
    /**
     * When mining of the block started, expressed in seconds since 1970-01-01.
     *
     * Generated from protobuf field <code>int64 timestamp = 6;</code>
     */
    protected $timestamp = 0;
    /**
     * Difficulty in Compressed Target Format.
     *
     * Generated from protobuf field <code>uint32 bits = 7;</code>
     */
    protected $bits = 0;
    /**
     * A random value that was generated during block mining which happened to
     * result in a computed block hash below the difficulty target at the time.
     *
     * Generated from protobuf field <code>uint32 nonce = 8;</code>
     */
    protected $nonce = 0;
    /**
     * Number of blocks in a chain, including the block itself upon creation.
     *
     * Generated from protobuf field <code>int32 confirmations = 9;</code>
     */
    protected $confirmations = 0;
    /**
     * Difficulty target at time of creation.
     *
     * Generated from protobuf field <code>double difficulty = 10;</code>
     */
    protected $difficulty = 0.0;
    /**
     * Hash of the next block in this chain, little-endian.
     *
     * Generated from protobuf field <code>bytes next_block_hash = 11;</code>
     */
    protected $next_block_hash = '';
    /**
     * Size of the block in bytes.
     *
     * Generated from protobuf field <code>int32 size = 12;</code>
     */
    protected $size = 0;
    /**
     * The median block time of the latest 11 block timestamps.
     *
     * Generated from protobuf field <code>int64 median_time = 13;</code>
     */
    protected $median_time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hash
     *           The double sha256 hash of the six header fields in the first 80 bytes
     *           of the block, when encoded according the bitcoin protocol, little-endian.
     *           sha256(sha256(encoded_header))
     *     @type int $height
     *           The block number, an incremental index for each block mined.
     *     @type int $version
     *           A version number to track software/protocol upgrades.
     *     @type string $previous_block
     *           Hash of the previous block, little-endian.
     *     @type string $merkle_root
     *           The root of the Merkle Tree built from all transactions in the block, little-endian.
     *     @type int|string $timestamp
     *           When mining of the block started, expressed in seconds since 1970-01-01.
     *     @type int $bits
     *           Difficulty in Compressed Target Format.
     *     @type int $nonce
     *           A random value that was generated during block mining which happened to
     *           result in a computed block hash below the difficulty target at the time.
     *     @type int $confirmations
     *           Number of blocks in a chain, including the block itself upon creation.
     *     @type float $difficulty
     *           Difficulty target at time of creation.
     *     @type string $next_block_hash
     *           Hash of the next block in this chain, little-endian.
     *     @type int $size
     *           Size of the block in bytes.
     *     @type int|string $median_time
     *           The median block time of the latest 11 block timestamps.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * The double sha256 hash of the six header fields in the first 80 bytes
     * of the block, when encoded according the bitcoin protocol, little-endian.
     * sha256(sha256(encoded_header))
     *
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * The double sha256 hash of the six header fields in the first 80 bytes
     * of the block, when encoded according the bitcoin protocol, little-endian.
     * sha256(sha256(encoded_header))
     *
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

    /**
     * The block number, an incremental index for each block mined.
     *
     * Generated from protobuf field <code>int32 height = 2;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * The block number, an incremental index for each block mined.
     *
     * Generated from protobuf field <code>int32 height = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * A version number to track software/protocol upgrades.
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * A version number to track software/protocol upgrades.
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Hash of the previous block, little-endian.
     *
     * Generated from protobuf field <code>bytes previous_block = 4;</code>
     * @return string
     */
    public function getPreviousBlock()
    {
        return $this->previous_block;
    }

    /**
     * Hash of the previous block, little-endian.
     *
     * Generated from protobuf field <code>bytes previous_block = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPreviousBlock($var)
    {
        GPBUtil::checkString($var, False);
        $this->previous_block = $var;

        return $this;
    }

    /**
     * The root of the Merkle Tree built from all transactions in the block, little-endian.
     *
     * Generated from protobuf field <code>bytes merkle_root = 5;</code>
     * @return string
     */
    public function getMerkleRoot()
    {
        return $this->merkle_root;
    }

    /**
     * The root of the Merkle Tree built from all transactions in the block, little-endian.
     *
     * Generated from protobuf field <code>bytes merkle_root = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMerkleRoot($var)
    {
        GPBUtil::checkString($var, False);
        $this->merkle_root = $var;

        return $this;
    }

    /**
     * When mining of the block started, expressed in seconds since 1970-01-01.
     *
     * Generated from protobuf field <code>int64 timestamp = 6;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * When mining of the block started, expressed in seconds since 1970-01-01.
     *
     * Generated from protobuf field <code>int64 timestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Difficulty in Compressed Target Format.
     *
     * Generated from protobuf field <code>uint32 bits = 7;</code>
     * @return int
     */
    public function getBits()
    {
        return $this->bits;
    }

    /**
     * Difficulty in Compressed Target Format.
     *
     * Generated from protobuf field <code>uint32 bits = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setBits($var)
    {
        GPBUtil::checkUint32($var);
        $this->bits = $var;

        return $this;
    }

    /**
     * A random value that was generated during block mining which happened to
     * result in a computed block hash below the difficulty target at the time.
     *
     * Generated from protobuf field <code>uint32 nonce = 8;</code>
     * @return int
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * A random value that was generated during block mining which happened to
     * result in a computed block hash below the difficulty target at the time.
     *
     * Generated from protobuf field <code>uint32 nonce = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkUint32($var);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Number of blocks in a chain, including the block itself upon creation.
     *
     * Generated from protobuf field <code>int32 confirmations = 9;</code>
     * @return int
     */
    public function getConfirmations()
    {
        return $this->confirmations;
    }

    /**
     * Number of blocks in a chain, including the block itself upon creation.
     *
     * Generated from protobuf field <code>int32 confirmations = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setConfirmations($var)
    {
        GPBUtil::checkInt32($var);
        $this->confirmations = $var;

        return $this;
    }

    /**
     * Difficulty target at time of creation.
     *
     * Generated from protobuf field <code>double difficulty = 10;</code>
     * @return float
     */
    public function getDifficulty()
    {
        return $this->difficulty;
    }

    /**
     * Difficulty target at time of creation.
     *
     * Generated from protobuf field <code>double difficulty = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setDifficulty($var)
    {
        GPBUtil::checkDouble($var);
        $this->difficulty = $var;

        return $this;
    }

    /**
     * Hash of the next block in this chain, little-endian.
     *
     * Generated from protobuf field <code>bytes next_block_hash = 11;</code>
     * @return string
     */
    public function getNextBlockHash()
    {
        return $this->next_block_hash;
    }

    /**
     * Hash of the next block in this chain, little-endian.
     *
     * Generated from protobuf field <code>bytes next_block_hash = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setNextBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->next_block_hash = $var;

        return $this;
    }

    /**
     * Size of the block in bytes.
     *
     * Generated from protobuf field <code>int32 size = 12;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Size of the block in bytes.
     *
     * Generated from protobuf field <code>int32 size = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;

        return $this;
    }

    /**
     * The median block time of the latest 11 block timestamps.
     *
     * Generated from protobuf field <code>int64 median_time = 13;</code>
     * @return int|string
     */
    public function getMedianTime()
    {
        return $this->median_time;
    }

    /**
     * The median block time of the latest 11 block timestamps.
     *
     * Generated from protobuf field <code>int64 median_time = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMedianTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->median_time = $var;

        return $this;
    }

}

