<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\Block\TransactionData instead.
     * @deprecated
     */
    class Block_TransactionData {}
}
class_exists(Block\TransactionData::class);
@trigger_error('Pb\Block_TransactionData is deprecated and will be removed in the next major release. Use Pb\Block\TransactionData instead', E_USER_DEPRECATED);

