<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.BlockInfo</code>
 */
class BlockInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Identification.
     *
     * Generated from protobuf field <code>bytes hash = 1;</code>
     */
    protected $hash = '';
    /**
     * Generated from protobuf field <code>int32 height = 2;</code>
     */
    protected $height = 0;
    /**
     * Block header data.
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>bytes previous_block = 4;</code>
     */
    protected $previous_block = '';
    /**
     * Generated from protobuf field <code>bytes merkle_root = 5;</code>
     */
    protected $merkle_root = '';
    /**
     * Generated from protobuf field <code>int64 timestamp = 6;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>uint32 bits = 7;</code>
     */
    protected $bits = 0;
    /**
     * Generated from protobuf field <code>uint32 nonce = 8;</code>
     */
    protected $nonce = 0;
    /**
     * Metadata.
     *
     * Generated from protobuf field <code>int32 confirmations = 9;</code>
     */
    protected $confirmations = 0;
    /**
     * Generated from protobuf field <code>double difficulty = 10;</code>
     */
    protected $difficulty = 0.0;
    /**
     * Generated from protobuf field <code>bytes next_block_hash = 11;</code>
     */
    protected $next_block_hash = '';
    /**
     * Generated from protobuf field <code>int32 size = 12;</code>
     */
    protected $size = 0;
    /**
     * Generated from protobuf field <code>int64 median_time = 13;</code>
     */
    protected $median_time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hash
     *           Identification.
     *     @type int $height
     *     @type int $version
     *           Block header data.
     *     @type string $previous_block
     *     @type string $merkle_root
     *     @type int|string $timestamp
     *     @type int $bits
     *     @type int $nonce
     *     @type int $confirmations
     *           Metadata.
     *     @type float $difficulty
     *     @type string $next_block_hash
     *     @type int $size
     *     @type int|string $median_time
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Identification.
     *
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Identification.
     *
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 height = 2;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int32 height = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Block header data.
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Block header data.
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes previous_block = 4;</code>
     * @return string
     */
    public function getPreviousBlock()
    {
        return $this->previous_block;
    }

    /**
     * Generated from protobuf field <code>bytes previous_block = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPreviousBlock($var)
    {
        GPBUtil::checkString($var, False);
        $this->previous_block = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes merkle_root = 5;</code>
     * @return string
     */
    public function getMerkleRoot()
    {
        return $this->merkle_root;
    }

    /**
     * Generated from protobuf field <code>bytes merkle_root = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMerkleRoot($var)
    {
        GPBUtil::checkString($var, False);
        $this->merkle_root = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 6;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 bits = 7;</code>
     * @return int
     */
    public function getBits()
    {
        return $this->bits;
    }

    /**
     * Generated from protobuf field <code>uint32 bits = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setBits($var)
    {
        GPBUtil::checkUint32($var);
        $this->bits = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 nonce = 8;</code>
     * @return int
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * Generated from protobuf field <code>uint32 nonce = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkUint32($var);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Metadata.
     *
     * Generated from protobuf field <code>int32 confirmations = 9;</code>
     * @return int
     */
    public function getConfirmations()
    {
        return $this->confirmations;
    }

    /**
     * Metadata.
     *
     * Generated from protobuf field <code>int32 confirmations = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setConfirmations($var)
    {
        GPBUtil::checkInt32($var);
        $this->confirmations = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double difficulty = 10;</code>
     * @return float
     */
    public function getDifficulty()
    {
        return $this->difficulty;
    }

    /**
     * Generated from protobuf field <code>double difficulty = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setDifficulty($var)
    {
        GPBUtil::checkDouble($var);
        $this->difficulty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes next_block_hash = 11;</code>
     * @return string
     */
    public function getNextBlockHash()
    {
        return $this->next_block_hash;
    }

    /**
     * Generated from protobuf field <code>bytes next_block_hash = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setNextBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->next_block_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 size = 12;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>int32 size = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 median_time = 13;</code>
     * @return int|string
     */
    public function getMedianTime()
    {
        return $this->median_time;
    }

    /**
     * Generated from protobuf field <code>int64 median_time = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMedianTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->median_time = $var;

        return $this;
    }

}

