<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\BlockNotification\Type instead.
     * @deprecated
     */
    class BlockNotification_Type {}
}
class_exists(BlockNotification\Type::class);
@trigger_error('Pb\BlockNotification_Type is deprecated and will be removed in the next major release. Use Pb\BlockNotification\Type instead', E_USER_DEPRECATED);

