<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetAddressTransactionsRequest</code>
 */
class GetAddressTransactionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    protected $address = '';
    /**
     * Control the number of transactions to be fetched from the blockchain.
     * These controls only apply to the confirmed transactions. All unconfirmed
     * ones will be returned always.
     *
     * Generated from protobuf field <code>uint32 nb_skip = 2;</code>
     */
    protected $nb_skip = 0;
    /**
     * Generated from protobuf field <code>uint32 nb_fetch = 3;</code>
     */
    protected $nb_fetch = 0;
    protected $start_block;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type int $nb_skip
     *           Control the number of transactions to be fetched from the blockchain.
     *           These controls only apply to the confirmed transactions. All unconfirmed
     *           ones will be returned always.
     *     @type int $nb_fetch
     *     @type string $hash
     *     @type int $height
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Control the number of transactions to be fetched from the blockchain.
     * These controls only apply to the confirmed transactions. All unconfirmed
     * ones will be returned always.
     *
     * Generated from protobuf field <code>uint32 nb_skip = 2;</code>
     * @return int
     */
    public function getNbSkip()
    {
        return $this->nb_skip;
    }

    /**
     * Control the number of transactions to be fetched from the blockchain.
     * These controls only apply to the confirmed transactions. All unconfirmed
     * ones will be returned always.
     *
     * Generated from protobuf field <code>uint32 nb_skip = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNbSkip($var)
    {
        GPBUtil::checkUint32($var);
        $this->nb_skip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 nb_fetch = 3;</code>
     * @return int
     */
    public function getNbFetch()
    {
        return $this->nb_fetch;
    }

    /**
     * Generated from protobuf field <code>uint32 nb_fetch = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNbFetch($var)
    {
        GPBUtil::checkUint32($var);
        $this->nb_fetch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 4;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>bytes hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 height = 5;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>int32 height = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getStartBlock()
    {
        return $this->whichOneof("start_block");
    }

}

