<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetAddressTransactionsResponse</code>
 */
class GetAddressTransactionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Transactions that have been included in a block.
     *
     * Generated from protobuf field <code>repeated .pb.Transaction confirmed_transactions = 1;</code>
     */
    private $confirmed_transactions;
    /**
     * Transactions in mempool which have not been included in a block.
     *
     * Generated from protobuf field <code>repeated .pb.MempoolTransaction unconfirmed_transactions = 2;</code>
     */
    private $unconfirmed_transactions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pb\Transaction[]|\Google\Protobuf\Internal\RepeatedField $confirmed_transactions
     *           Transactions that have been included in a block.
     *     @type \Pb\MempoolTransaction[]|\Google\Protobuf\Internal\RepeatedField $unconfirmed_transactions
     *           Transactions in mempool which have not been included in a block.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Transactions that have been included in a block.
     *
     * Generated from protobuf field <code>repeated .pb.Transaction confirmed_transactions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConfirmedTransactions()
    {
        return $this->confirmed_transactions;
    }

    /**
     * Transactions that have been included in a block.
     *
     * Generated from protobuf field <code>repeated .pb.Transaction confirmed_transactions = 1;</code>
     * @param \Pb\Transaction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConfirmedTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\Transaction::class);
        $this->confirmed_transactions = $arr;

        return $this;
    }

    /**
     * Transactions in mempool which have not been included in a block.
     *
     * Generated from protobuf field <code>repeated .pb.MempoolTransaction unconfirmed_transactions = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnconfirmedTransactions()
    {
        return $this->unconfirmed_transactions;
    }

    /**
     * Transactions in mempool which have not been included in a block.
     *
     * Generated from protobuf field <code>repeated .pb.MempoolTransaction unconfirmed_transactions = 2;</code>
     * @param \Pb\MempoolTransaction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnconfirmedTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\MempoolTransaction::class);
        $this->unconfirmed_transactions = $arr;

        return $this;
    }

}

