<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetBlockRequest</code>
 */
class GetBlockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Provide full transaction info instead of only the hashes.
     *
     * Generated from protobuf field <code>bool full_transactions = 3;</code>
     */
    protected $full_transactions = false;
    protected $hash_or_height;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hash
     *     @type int $height
     *     @type bool $full_transactions
     *           Provide full transaction info instead of only the hashes.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 height = 2;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>int32 height = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Provide full transaction info instead of only the hashes.
     *
     * Generated from protobuf field <code>bool full_transactions = 3;</code>
     * @return bool
     */
    public function getFullTransactions()
    {
        return $this->full_transactions;
    }

    /**
     * Provide full transaction info instead of only the hashes.
     *
     * Generated from protobuf field <code>bool full_transactions = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setFullTransactions($var)
    {
        GPBUtil::checkBool($var);
        $this->full_transactions = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getHashOrHeight()
    {
        return $this->whichOneof("hash_or_height");
    }

}

