<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetBlockFilterResponse</code>
 */
class GetBlockFilterResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * A compact filter matching input outpoints and public key scripts contained
     * in a block (encoded according to BIP158).
     *
     * Generated from protobuf field <code>bytes filter = 1;</code>
     */
    protected $filter = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $filter
     *           A compact filter matching input outpoints and public key scripts contained
     *           in a block (encoded according to BIP158).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * A compact filter matching input outpoints and public key scripts contained
     * in a block (encoded according to BIP158).
     *
     * Generated from protobuf field <code>bytes filter = 1;</code>
     * @return string
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * A compact filter matching input outpoints and public key scripts contained
     * in a block (encoded according to BIP158).
     *
     * Generated from protobuf field <code>bytes filter = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, False);
        $this->filter = $var;

        return $this;
    }

}

