<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetBlockInfoResponse</code>
 */
class GetBlockInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Marshaled block header data, as well as metadata.
     *
     * Generated from protobuf field <code>.pb.BlockInfo info = 1;</code>
     */
    protected $info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pb\BlockInfo $info
     *           Marshaled block header data, as well as metadata.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Marshaled block header data, as well as metadata.
     *
     * Generated from protobuf field <code>.pb.BlockInfo info = 1;</code>
     * @return \Pb\BlockInfo
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Marshaled block header data, as well as metadata.
     *
     * Generated from protobuf field <code>.pb.BlockInfo info = 1;</code>
     * @param \Pb\BlockInfo $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \Pb\BlockInfo::class);
        $this->info = $var;

        return $this;
    }

}

