<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetBlockchainInfoResponse</code>
 */
class GetBlockchainInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pb.GetBlockchainInfoResponse.BitcoinNet bitcoin_net = 1;</code>
     */
    protected $bitcoin_net = 0;
    /**
     * Generated from protobuf field <code>int32 best_height = 2;</code>
     */
    protected $best_height = 0;
    /**
     * Generated from protobuf field <code>bytes best_block_hash = 3;</code>
     */
    protected $best_block_hash = '';
    /**
     * Generated from protobuf field <code>double difficulty = 4;</code>
     */
    protected $difficulty = 0.0;
    /**
     * Generated from protobuf field <code>int64 median_time = 5;</code>
     */
    protected $median_time = 0;
    /**
     * Generated from protobuf field <code>bool tx_index = 6;</code>
     */
    protected $tx_index = false;
    /**
     * Generated from protobuf field <code>bool addr_index = 7;</code>
     */
    protected $addr_index = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $bitcoin_net
     *     @type int $best_height
     *     @type string $best_block_hash
     *     @type float $difficulty
     *     @type int|string $median_time
     *     @type bool $tx_index
     *     @type bool $addr_index
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pb.GetBlockchainInfoResponse.BitcoinNet bitcoin_net = 1;</code>
     * @return int
     */
    public function getBitcoinNet()
    {
        return $this->bitcoin_net;
    }

    /**
     * Generated from protobuf field <code>.pb.GetBlockchainInfoResponse.BitcoinNet bitcoin_net = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBitcoinNet($var)
    {
        GPBUtil::checkEnum($var, \Pb\GetBlockchainInfoResponse_BitcoinNet::class);
        $this->bitcoin_net = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 best_height = 2;</code>
     * @return int
     */
    public function getBestHeight()
    {
        return $this->best_height;
    }

    /**
     * Generated from protobuf field <code>int32 best_height = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBestHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->best_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes best_block_hash = 3;</code>
     * @return string
     */
    public function getBestBlockHash()
    {
        return $this->best_block_hash;
    }

    /**
     * Generated from protobuf field <code>bytes best_block_hash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBestBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->best_block_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double difficulty = 4;</code>
     * @return float
     */
    public function getDifficulty()
    {
        return $this->difficulty;
    }

    /**
     * Generated from protobuf field <code>double difficulty = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setDifficulty($var)
    {
        GPBUtil::checkDouble($var);
        $this->difficulty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 median_time = 5;</code>
     * @return int|string
     */
    public function getMedianTime()
    {
        return $this->median_time;
    }

    /**
     * Generated from protobuf field <code>int64 median_time = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMedianTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->median_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool tx_index = 6;</code>
     * @return bool
     */
    public function getTxIndex()
    {
        return $this->tx_index;
    }

    /**
     * Generated from protobuf field <code>bool tx_index = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setTxIndex($var)
    {
        GPBUtil::checkBool($var);
        $this->tx_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool addr_index = 7;</code>
     * @return bool
     */
    public function getAddrIndex()
    {
        return $this->addr_index;
    }

    /**
     * Generated from protobuf field <code>bool addr_index = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddrIndex($var)
    {
        GPBUtil::checkBool($var);
        $this->addr_index = $var;

        return $this;
    }

}

