<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\GetBlockchainInfoResponse\BitcoinNet instead.
     * @deprecated
     */
    class GetBlockchainInfoResponse_BitcoinNet {}
}
class_exists(GetBlockchainInfoResponse\BitcoinNet::class);
@trigger_error('Pb\GetBlockchainInfoResponse_BitcoinNet is deprecated and will be removed in the next major release. Use Pb\GetBlockchainInfoResponse\BitcoinNet instead', E_USER_DEPRECATED);

