<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetHeadersRequest</code>
 */
class GetHeadersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes block_locator_hashes = 1;</code>
     */
    private $block_locator_hashes;
    /**
     * Generated from protobuf field <code>bytes stop_hash = 2;</code>
     */
    protected $stop_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $block_locator_hashes
     *     @type string $stop_hash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes block_locator_hashes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBlockLocatorHashes()
    {
        return $this->block_locator_hashes;
    }

    /**
     * Generated from protobuf field <code>repeated bytes block_locator_hashes = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBlockLocatorHashes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->block_locator_hashes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes stop_hash = 2;</code>
     * @return string
     */
    public function getStopHash()
    {
        return $this->stop_hash;
    }

    /**
     * Generated from protobuf field <code>bytes stop_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStopHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->stop_hash = $var;

        return $this;
    }

}

