<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetHeadersResponse</code>
 */
class GetHeadersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * List of block headers.
     *
     * Generated from protobuf field <code>repeated .pb.BlockInfo headers = 1;</code>
     */
    private $headers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pb\BlockInfo[]|\Google\Protobuf\Internal\RepeatedField $headers
     *           List of block headers.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * List of block headers.
     *
     * Generated from protobuf field <code>repeated .pb.BlockInfo headers = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * List of block headers.
     *
     * Generated from protobuf field <code>repeated .pb.BlockInfo headers = 1;</code>
     * @param \Pb\BlockInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\BlockInfo::class);
        $this->headers = $arr;

        return $this;
    }

}

