<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request headers using a list of known block hashes.
 *
 * Generated from protobuf message <code>pb.GetHeadersRequest</code>
 */
class GetHeadersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of block hashes known to the client (most recent first) which
     * is exponentially sparser toward the genesis block (0), little-endian.
     * Common practice is to include all of the last 10 blocks, and then
     * 9 blocks for each order of ten thereafter.
     *
     * Generated from protobuf field <code>repeated bytes block_locator_hashes = 1;</code>
     */
    private $block_locator_hashes;
    /**
     * hash of the latest desired block header, little-endian; only blocks
     * occurring before the stop will be returned.
     *
     * Generated from protobuf field <code>bytes stop_hash = 2;</code>
     */
    protected $stop_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $block_locator_hashes
     *           A list of block hashes known to the client (most recent first) which
     *           is exponentially sparser toward the genesis block (0), little-endian.
     *           Common practice is to include all of the last 10 blocks, and then
     *           9 blocks for each order of ten thereafter.
     *     @type string $stop_hash
     *           hash of the latest desired block header, little-endian; only blocks
     *           occurring before the stop will be returned.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of block hashes known to the client (most recent first) which
     * is exponentially sparser toward the genesis block (0), little-endian.
     * Common practice is to include all of the last 10 blocks, and then
     * 9 blocks for each order of ten thereafter.
     *
     * Generated from protobuf field <code>repeated bytes block_locator_hashes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBlockLocatorHashes()
    {
        return $this->block_locator_hashes;
    }

    /**
     * A list of block hashes known to the client (most recent first) which
     * is exponentially sparser toward the genesis block (0), little-endian.
     * Common practice is to include all of the last 10 blocks, and then
     * 9 blocks for each order of ten thereafter.
     *
     * Generated from protobuf field <code>repeated bytes block_locator_hashes = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBlockLocatorHashes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->block_locator_hashes = $arr;

        return $this;
    }

    /**
     * hash of the latest desired block header, little-endian; only blocks
     * occurring before the stop will be returned.
     *
     * Generated from protobuf field <code>bytes stop_hash = 2;</code>
     * @return string
     */
    public function getStopHash()
    {
        return $this->stop_hash;
    }

    /**
     * hash of the latest desired block header, little-endian; only blocks
     * occurring before the stop will be returned.
     *
     * Generated from protobuf field <code>bytes stop_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStopHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->stop_hash = $var;

        return $this;
    }

}

