<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetMerkleProofResponse</code>
 */
class GetMerkleProofResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pb.BlockInfo block = 1;</code>
     */
    protected $block = null;
    /**
     * Generated from protobuf field <code>repeated bytes hashes = 2;</code>
     */
    private $hashes;
    /**
     * Generated from protobuf field <code>bytes flags = 3;</code>
     */
    protected $flags = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pb\BlockInfo $block
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $hashes
     *     @type string $flags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pb.BlockInfo block = 1;</code>
     * @return \Pb\BlockInfo
     */
    public function getBlock()
    {
        return $this->block;
    }

    /**
     * Generated from protobuf field <code>.pb.BlockInfo block = 1;</code>
     * @param \Pb\BlockInfo $var
     * @return $this
     */
    public function setBlock($var)
    {
        GPBUtil::checkMessage($var, \Pb\BlockInfo::class);
        $this->block = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes hashes = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHashes()
    {
        return $this->hashes;
    }

    /**
     * Generated from protobuf field <code>repeated bytes hashes = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHashes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->hashes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes flags = 3;</code>
     * @return string
     */
    public function getFlags()
    {
        return $this->flags;
    }

    /**
     * Generated from protobuf field <code>bytes flags = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFlags($var)
    {
        GPBUtil::checkString($var, False);
        $this->flags = $var;

        return $this;
    }

}

