<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetMempoolRequest</code>
 */
class GetMempoolRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Provide full transaction info instead of only the hashes.
     *
     * Generated from protobuf field <code>bool full_transactions = 1;</code>
     */
    protected $full_transactions = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $full_transactions
     *           Provide full transaction info instead of only the hashes.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Provide full transaction info instead of only the hashes.
     *
     * Generated from protobuf field <code>bool full_transactions = 1;</code>
     * @return bool
     */
    public function getFullTransactions()
    {
        return $this->full_transactions;
    }

    /**
     * Provide full transaction info instead of only the hashes.
     *
     * Generated from protobuf field <code>bool full_transactions = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setFullTransactions($var)
    {
        GPBUtil::checkBool($var);
        $this->full_transactions = $var;

        return $this;
    }

}

