<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\GetMempoolResponse\TransactionData instead.
     * @deprecated
     */
    class GetMempoolResponse_TransactionData {}
}
class_exists(GetMempoolResponse\TransactionData::class);
@trigger_error('Pb\GetMempoolResponse_TransactionData is deprecated and will be removed in the next major release. Use Pb\GetMempoolResponse\TransactionData instead', E_USER_DEPRECATED);

