<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.GetUnspentOutputResponse</code>
 */
class GetUnspentOutputResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * A reference to the related input.
     *
     * Generated from protobuf field <code>.pb.Transaction.Input.Outpoint outpoint = 1;</code>
     */
    protected $outpoint = null;
    /**
     * Locking script dictating how funds can be spent in the future
     *
     * Generated from protobuf field <code>bytes pubkey_script = 2;</code>
     */
    protected $pubkey_script = '';
    /**
     * Amount in satoshi.
     *
     * Generated from protobuf field <code>int64 value = 3;</code>
     */
    protected $value = 0;
    /**
     * When is_coinbase is true, the transaction was the first in a block,
     * created by a miner, and used to pay the block reward
     *
     * Generated from protobuf field <code>bool is_coinbase = 4;</code>
     */
    protected $is_coinbase = false;
    /**
     * The index number of the block containing the transaction creating the output.
     *
     * Generated from protobuf field <code>int32 block_height = 5;</code>
     */
    protected $block_height = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pb\Transaction\Input\Outpoint $outpoint
     *           A reference to the related input.
     *     @type string $pubkey_script
     *           Locking script dictating how funds can be spent in the future
     *     @type int|string $value
     *           Amount in satoshi.
     *     @type bool $is_coinbase
     *           When is_coinbase is true, the transaction was the first in a block,
     *           created by a miner, and used to pay the block reward
     *     @type int $block_height
     *           The index number of the block containing the transaction creating the output.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * A reference to the related input.
     *
     * Generated from protobuf field <code>.pb.Transaction.Input.Outpoint outpoint = 1;</code>
     * @return \Pb\Transaction\Input\Outpoint
     */
    public function getOutpoint()
    {
        return $this->outpoint;
    }

    /**
     * A reference to the related input.
     *
     * Generated from protobuf field <code>.pb.Transaction.Input.Outpoint outpoint = 1;</code>
     * @param \Pb\Transaction\Input\Outpoint $var
     * @return $this
     */
    public function setOutpoint($var)
    {
        GPBUtil::checkMessage($var, \Pb\Transaction\Input\Outpoint::class);
        $this->outpoint = $var;

        return $this;
    }

    /**
     * Locking script dictating how funds can be spent in the future
     *
     * Generated from protobuf field <code>bytes pubkey_script = 2;</code>
     * @return string
     */
    public function getPubkeyScript()
    {
        return $this->pubkey_script;
    }

    /**
     * Locking script dictating how funds can be spent in the future
     *
     * Generated from protobuf field <code>bytes pubkey_script = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPubkeyScript($var)
    {
        GPBUtil::checkString($var, False);
        $this->pubkey_script = $var;

        return $this;
    }

    /**
     * Amount in satoshi.
     *
     * Generated from protobuf field <code>int64 value = 3;</code>
     * @return int|string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Amount in satoshi.
     *
     * Generated from protobuf field <code>int64 value = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->value = $var;

        return $this;
    }

    /**
     * When is_coinbase is true, the transaction was the first in a block,
     * created by a miner, and used to pay the block reward
     *
     * Generated from protobuf field <code>bool is_coinbase = 4;</code>
     * @return bool
     */
    public function getIsCoinbase()
    {
        return $this->is_coinbase;
    }

    /**
     * When is_coinbase is true, the transaction was the first in a block,
     * created by a miner, and used to pay the block reward
     *
     * Generated from protobuf field <code>bool is_coinbase = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCoinbase($var)
    {
        GPBUtil::checkBool($var);
        $this->is_coinbase = $var;

        return $this;
    }

    /**
     * The index number of the block containing the transaction creating the output.
     *
     * Generated from protobuf field <code>int32 block_height = 5;</code>
     * @return int
     */
    public function getBlockHeight()
    {
        return $this->block_height;
    }

    /**
     * The index number of the block containing the transaction creating the output.
     *
     * Generated from protobuf field <code>int32 block_height = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBlockHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->block_height = $var;

        return $this;
    }

}

