<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\Transaction\Input instead.
     * @deprecated
     */
    class Transaction_Input {}
}
class_exists(Transaction\Input::class);
@trigger_error('Pb\Transaction_Input is deprecated and will be removed in the next major release. Use Pb\Transaction\Input instead', E_USER_DEPRECATED);

