<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\Transaction\Output instead.
     * @deprecated
     */
    class Transaction_Output {}
}
class_exists(Transaction\Output::class);
@trigger_error('Pb\Transaction_Output is deprecated and will be removed in the next major release. Use Pb\Transaction\Output instead', E_USER_DEPRECATED);

