<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\TransactionNotification\Type instead.
     * @deprecated
     */
    class TransactionNotification_Type {}
}
class_exists(TransactionNotification\Type::class);
@trigger_error('Pb\TransactionNotification_Type is deprecated and will be removed in the next major release. Use Pb\TransactionNotification\Type instead', E_USER_DEPRECATED);

