<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\Transaction\Input\Outpoint instead.
     * @deprecated
     */
    class Transaction_Input_Outpoint {}
}
class_exists(Transaction\Input\Outpoint::class);
@trigger_error('Pb\Transaction_Input_Outpoint is deprecated and will be removed in the next major release. Use Pb\Transaction\Input\Outpoint instead', E_USER_DEPRECATED);

