<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.TransactionNotification</code>
 */
class TransactionNotification extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether or not the transaction has been included in a block.
     *
     * Generated from protobuf field <code>.pb.TransactionNotification.Type type = 1;</code>
     */
    protected $type = 0;
    protected $transaction;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           Whether or not the transaction has been included in a block.
     *     @type \Pb\Transaction $confirmed_transaction
     *           A transaction included in a block.
     *     @type \Pb\MempoolTransaction $unconfirmed_transaction
     *           A transaction in mempool.
     *     @type string $serialized_transaction
     *           Binary transaction, serialized using bitcoin protocol encoding.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Whether or not the transaction has been included in a block.
     *
     * Generated from protobuf field <code>.pb.TransactionNotification.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Whether or not the transaction has been included in a block.
     *
     * Generated from protobuf field <code>.pb.TransactionNotification.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Pb\TransactionNotification\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * A transaction included in a block.
     *
     * Generated from protobuf field <code>.pb.Transaction confirmed_transaction = 2;</code>
     * @return \Pb\Transaction
     */
    public function getConfirmedTransaction()
    {
        return $this->readOneof(2);
    }

    /**
     * A transaction included in a block.
     *
     * Generated from protobuf field <code>.pb.Transaction confirmed_transaction = 2;</code>
     * @param \Pb\Transaction $var
     * @return $this
     */
    public function setConfirmedTransaction($var)
    {
        GPBUtil::checkMessage($var, \Pb\Transaction::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * A transaction in mempool.
     *
     * Generated from protobuf field <code>.pb.MempoolTransaction unconfirmed_transaction = 3;</code>
     * @return \Pb\MempoolTransaction
     */
    public function getUnconfirmedTransaction()
    {
        return $this->readOneof(3);
    }

    /**
     * A transaction in mempool.
     *
     * Generated from protobuf field <code>.pb.MempoolTransaction unconfirmed_transaction = 3;</code>
     * @param \Pb\MempoolTransaction $var
     * @return $this
     */
    public function setUnconfirmedTransaction($var)
    {
        GPBUtil::checkMessage($var, \Pb\MempoolTransaction::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Binary transaction, serialized using bitcoin protocol encoding.
     *
     * Generated from protobuf field <code>bytes serialized_transaction = 4;</code>
     * @return string
     */
    public function getSerializedTransaction()
    {
        return $this->readOneof(4);
    }

    /**
     * Binary transaction, serialized using bitcoin protocol encoding.
     *
     * Generated from protobuf field <code>bytes serialized_transaction = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSerializedTransaction($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getTransaction()
    {
        return $this->whichOneof("transaction");
    }

}

