<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.TransactionFilter</code>
 */
class TransactionFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string addresses = 1;</code>
     */
    private $addresses;
    /**
     * Generated from protobuf field <code>repeated .pb.Transaction.Input.Outpoint outpoints = 2;</code>
     */
    private $outpoints;
    /**
     * Generated from protobuf field <code>repeated bytes data_elements = 3;</code>
     */
    private $data_elements;
    /**
     * Subscribed/Unsubscribe to everything. Other filters
     * will be ignored.
     *
     * Generated from protobuf field <code>bool all_transactions = 4;</code>
     */
    protected $all_transactions = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $addresses
     *     @type \Pb\Transaction\Input\Outpoint[]|\Google\Protobuf\Internal\RepeatedField $outpoints
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $data_elements
     *     @type bool $all_transactions
     *           Subscribed/Unsubscribe to everything. Other filters
     *           will be ignored.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string addresses = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Generated from protobuf field <code>repeated string addresses = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->addresses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Transaction.Input.Outpoint outpoints = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutpoints()
    {
        return $this->outpoints;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Transaction.Input.Outpoint outpoints = 2;</code>
     * @param \Pb\Transaction\Input\Outpoint[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutpoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\Transaction\Input\Outpoint::class);
        $this->outpoints = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes data_elements = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDataElements()
    {
        return $this->data_elements;
    }

    /**
     * Generated from protobuf field <code>repeated bytes data_elements = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDataElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->data_elements = $arr;

        return $this;
    }

    /**
     * Subscribed/Unsubscribe to everything. Other filters
     * will be ignored.
     *
     * Generated from protobuf field <code>bool all_transactions = 4;</code>
     * @return bool
     */
    public function getAllTransactions()
    {
        return $this->all_transactions;
    }

    /**
     * Subscribed/Unsubscribe to everything. Other filters
     * will be ignored.
     *
     * Generated from protobuf field <code>bool all_transactions = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllTransactions($var)
    {
        GPBUtil::checkBool($var);
        $this->all_transactions = $var;

        return $this;
    }

}

