<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bchrpc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     */
    protected $hash = '';
    /**
     * Generated from protobuf field <code>int32 version = 2;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>repeated .pb.Transaction.Input inputs = 3;</code>
     */
    private $inputs;
    /**
     * Generated from protobuf field <code>repeated .pb.Transaction.Output outputs = 4;</code>
     */
    private $outputs;
    /**
     * Generated from protobuf field <code>uint32 lock_time = 5;</code>
     */
    protected $lock_time = 0;
    /**
     * Metadata
     *
     * Generated from protobuf field <code>int32 size = 8;</code>
     */
    protected $size = 0;
    /**
     * Generated from protobuf field <code>int64 timestamp = 9;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>int32 confirmations = 10;</code>
     */
    protected $confirmations = 0;
    /**
     * Generated from protobuf field <code>int32 block_height = 11;</code>
     */
    protected $block_height = 0;
    /**
     * Generated from protobuf field <code>bytes block_hash = 12;</code>
     */
    protected $block_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hash
     *     @type int $version
     *     @type \Pb\Transaction\Input[]|\Google\Protobuf\Internal\RepeatedField $inputs
     *     @type \Pb\Transaction\Output[]|\Google\Protobuf\Internal\RepeatedField $outputs
     *     @type int $lock_time
     *     @type int $size
     *           Metadata
     *     @type int|string $timestamp
     *     @type int $confirmations
     *     @type int $block_height
     *     @type string $block_hash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bchrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 version = 2;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Transaction.Input inputs = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInputs()
    {
        return $this->inputs;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Transaction.Input inputs = 3;</code>
     * @param \Pb\Transaction\Input[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\Transaction\Input::class);
        $this->inputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Transaction.Output outputs = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutputs()
    {
        return $this->outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Transaction.Output outputs = 4;</code>
     * @param \Pb\Transaction\Output[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\Transaction\Output::class);
        $this->outputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 lock_time = 5;</code>
     * @return int
     */
    public function getLockTime()
    {
        return $this->lock_time;
    }

    /**
     * Generated from protobuf field <code>uint32 lock_time = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLockTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->lock_time = $var;

        return $this;
    }

    /**
     * Metadata
     *
     * Generated from protobuf field <code>int32 size = 8;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Metadata
     *
     * Generated from protobuf field <code>int32 size = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 9;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 confirmations = 10;</code>
     * @return int
     */
    public function getConfirmations()
    {
        return $this->confirmations;
    }

    /**
     * Generated from protobuf field <code>int32 confirmations = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setConfirmations($var)
    {
        GPBUtil::checkInt32($var);
        $this->confirmations = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 block_height = 11;</code>
     * @return int
     */
    public function getBlockHeight()
    {
        return $this->block_height;
    }

    /**
     * Generated from protobuf field <code>int32 block_height = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setBlockHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->block_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes block_hash = 12;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->block_hash;
    }

    /**
     * Generated from protobuf field <code>bytes block_hash = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->block_hash = $var;

        return $this;
    }

}

